---
name: Unit Test

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  run-ci:
    name: NPM CI

    # https://docs.github.com/en/actions/security-guides/automatic-token-authentication
    permissions:
      checks: "write"
      contents: "read"
      issues: "read"
      pull-requests: "write"

    uses: nodejs-yarn-unit-tests.yaml
    secrets: inherit
    with:
      nodejs-version: "20.9.0"
